name: askleave
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - sqlalchemy==2.0.23
    - pydantic==2.5.0
    - python-jose[cryptography]==3.3.0
    - passlib[bcrypt]==1.7.4
    - python-multipart==0.0.6
    - langchain==0.1.0
    - langchain-openai==0.0.5
    - langchain-community==0.0.13
    - openai==1.3.7
    - faiss-cpu==1.7.4
    - tiktoken==0.5.1
    - python-dotenv==1.0.0
    - alembic==1.12.1
    - pymysql==1.1.0
    - psycopg2-binary==2.9.9
    - redis==5.0.1
    - chromadb==0.4.22
    - pypdf==3.17.1
    - docx2txt==0.8
    - pandas==2.1.1 